name: Manual Database Reset

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to reset'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - development
      confirm:
        description: 'Type "RESET" to confirm'
        required: true
        type: string

jobs:
  reset-database:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'RESET'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: coffee_shop_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/coffee_shop_test" >> $GITHUB_ENV
        echo "NODE_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Reset database
      run: npm run db:reset

    - name: Seed database
      run: |
        if [ -f "seed-database.js" ]; then
          npm run db:seed
        fi

    - name: Run tests to verify reset
      run: npm run test:ci

    - name: Comment on trigger
      uses: actions/github-script@v7
      with:
        script: |
          const body = `✅ Database reset completed for **${{ github.event.inputs.environment }}** environment.
          
          **Triggered by:** @${{ github.actor }}
          **Commit:** \`${{ github.sha }}\`
          **Time:** ${new Date().toISOString()}
          
          All tests are passing after the reset.`;
          
          // Create an issue comment or discussion
          console.log(body);
